---
- name: Ping'em all!
  gather_facts: no
  hosts: all

  #Wait for the SSH agent to get alive and gather facts
  pre_tasks:
  - name: Wait for connection
    wait_for_connection:
      delay: 15
      timeout: 60

  tasks:
  - name: Gather facts
    setup:
  
  - name: Ping'em all!
    ping: